spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  application:
    name: TripleA

application:
  security:
    jwt:
      secret-key: rWXmwH1UyBGgF8U8Ytj/50d4PI8NSzyvfqadZSX1K0/eVLkMWRbz5jJGkIvnFoxz
      expiration: 3600000 # 1 hour
      refresh-token:
        expiration: 3600000 # 1 hour
server:
  port: 8080
  # address: 0.0.0.0
  # ssl:
  #   key-store: keystore.p12
  #   key-store-password: triplea
  #   keyStoreType: PKCS12
  #   keyAlias: tomcat

service-app:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://localhost:8088

logging:
  level:
    org:
    springframework:
      security: INFO
      web: INFO
      data: INFO
      hibernate: INFO
      jpa: INFO
      sql: INFO
      jwt: INFO
      service-app: INFO