groups:
  - name: AppAlerts
    rules:
      - alert: WARNING-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 50
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      
        # Quality metric - error rate
      - alert: WARNING-HighErrorRate
        expr: rate(getAllGamesErrors_total{endpoint="getAllGamesNegativeCount"}[10s]) > 0
        for: 1s
        labels:
          severity: warning
        annotations:
            summary: Increased get all games error rate {{ $labels.value}} {{ $value }}
            description: "The getAllGamesWithoutCount endpoint is experiencing a high error rate\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Performance metric
      - alert: WARNING-LowPerformanceGetAllGames
        expr: avg_over_time(getAllGames_time_seconds_max[10s]) > 0.2
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Low performance in getAllGames endpoint {{ $labels.value}} {{ $value }}
          description: "The getAllGames endpoint is experiencing low performance\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Availability metric - external Steam API
      - alert: CRITICAL-SteamApiError
        expr: rate(getAllGamesErrors_total{endpoint="getAllGamesApiError"}[10s]) > 0.1
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Steam API error {{ $labels.value}} {{ $value }}
          description: "The Steam API is experiencing errors\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
