pipeline {
    agent any
    environment {
        DOCKER_CREDS = credentials('docker_password')
        GITHUB_TOKEN = credentials('github_token')
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
                sh './gradlew testIT'
            }
        }

        stage('Tag & Push image') {
            steps {
                script {
                    sh([script: 'git fetch --tag', returnStdout: true]).trim()
                    env.MAJOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                    env.MINOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                    env.PATCH_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                    env.IMAGE_TAG = "${env.MAJOR_VERSION}.\$((${env.MINOR_VERSION} + 1)).${env.PATCH_VERSION}"
                    // // Fetch tags and determine next version
                    // sh('git fetch --tags')
                    // GIT_TAG = sh(script: "git describe --tags \$(git rev-list --tags --max-count=1)", returnStdout: true).trim()
                    // def (MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION) = GIT_TAG.tokenize('.')
                    
                    // // Increment minor version
                    // int newMinorVersion = MINOR_VERSION.toInteger() + 1
                    
                    // // Define the new image tag
                    // def newTag = "${MAJOR_VERSION}.${newMinorVersion}.${PATCH_VERSION}"
                    
                    // Build the Docker image with the new tag
                    sh "docker build -t ${DOCKER_CREDS_USR}/triplea-img:${env.IMAGE_TAG} ."
                    
                    // Log in and push the image
                    sh "echo ${DOCKER_CREDS_PSW} | docker login -u ${DOCKER_CREDS_USR} --password-stdin"
                    sh "docker push ${DOCKER_CREDS_USR}/triplea-img:${env.IMAGE_TAG}"

                    sh "git tag ${env.IMAGE_TAG}"
                    sh "git push https://$GITHUB_TOKEN@github.com/Triple-A-Unibuc/service.git ${env.IMAGE_TAG}"
                }
            }
        }
    }
}
